_wandb:
    value:
        cli_version: 0.22.0
        e:
            rnepxc0jaj6mkn4e39we6mp8dmguljo6:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "9408450560"
                email: juliaanswls@naver.com
                executable: /usr/local/bin/python
                host: b32685b21704
                memory:
                    total: "16720785408"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.36
                program: /opt/mlops/src/main.py
                python: CPython 3.11.13
                root: /opt/mlops/src
                startedAt: "2025-09-25T02:41:56.391828Z"
                writerId: rnepxc0jaj6mkn4e39we6mp8dmguljo6
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
                - 24
            "4": 3.11.13
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
n_epochs:
    value: 10
